### PR TITLE
fix: per platform overrides do not merge properly

### LINKED ISSUE #22: [Bug]: Per platform overrides do not properly merge
Tested rockspec: `lua-cjson@2.1.0.9-1`

The `win32` overrides remove the `sources` field, thus causing the deserializer to fail.

### PR DESCRIPTION
**Pull request by mrcjkb**
Fixes #22.

### CODE REVIEW

File: rocks-lib/src/rockspec/build/builtin.rs [hunk 1]
```diff
@@ -71,24 +73,94 @@ where
...
+}
+
+fn override_vec<T: Clone>(override_vec: &Vec<T>, base: &Vec<T>) -> Vec<T> {
+    // TODO: check luarocks codebase. Should this be overridden or merged?
+    // I would assume overriding makes more sense.
+    if override_vec.is_empty() {
+        return base.clone();
+    }
+    override_vec.clone()
+}
```
Comment (mrcjkb) [inline rocks-lib/src/rockspec/build/builtin.rs:162]: - [ ] TODO

**Review by vhyrro — APPROVED** [review]
