### PR TITLE
fix(build): copy `install.lib` files instead of compiling

### LINKED ISSUE #957: [bug] incorrect behavior when handling `build.install.lib` from rockspec
The rockspec format says this about the `build.install` field:

```
For packages which don't provide means to install modules and expect the user to copy the .lua or library files by hand to the proper locations. This table contains categories of files. Each category is itself a table, where the array part is a list of filenames to be copied. For module directories only, in the hash part, other keys are identifiers in Lua module format, to indicate which subdirectory the file should be copied to. For example, build.install.lua = {["foo.bar"] = "src/bar.lua"} will copy src/bar.lua to the foo directory under the rock's Lua files directory.
```

My understanding is that things under `build.install` should not be compiled, but instead merely copied to the package's directory. This behavior is implemented here: https://github.com/luarocks/luarocks/blob/99c57c8b2464550d6659cce43f84db83b17c4c15/src/luarocks/build/builtin.lua#L386-L394

In my library `luyoga` I need to copy the original library's header files, as well as the compiled shared libraries files, and I do so successfully with the following rockspec:

<details>
<summary>luyoga-1.3-3.rockspec</summary>

```
rockspec_format = "3.0"
package = "Luyoga"
version = "1.3-3"
source = {
   url = "git://github.com/SkyLeite/luyoga",
   tag = "v1.3-3"
}
description = {
   summary = "Lua bindings for facebook/yoga, a render-agnostic layouting engine",
   detailed = [[
      Lua bindings for the facebook/yoga layout library.
   ]],
   homepage = "https://skyleite.github.io/luyoga/",
   license = "LGPLv2.1"
}
dependencies = {
   "lua >= 5.1"
}
build = {
    type = "builtin",
    modules = {
        ["luyoga"] = "luyoga/init.lua",
        ["luyoga.layout"] = "luyoga/layout.lua",
        ["luyoga.enums"] = "luyoga/enums.lua",
        ["luyoga.node"] = "luyoga/node.lua",
        ["luyoga.style"] = "luyoga/style.lua",
        ["luyoga.util"] = "luyoga/util.lua",
        ["luyoga.value"] = "luyoga/value.lua",
    },
    install = {
      lib = {
        "dist/libyogacore.so",
        "dist/libyogacore.dylib",
        "dist/Yoga.h",
      },
    }
}
```

</details>

However, when attempting to install the library using `lx add luyoga`, I get the following error:

```
sky@Skys-MacBook-Air luyoga-test % cargo lx add luyoga
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.54s
     Running `/Users/sky/Projects/lux/target/debug/lx add luyoga`
⚠️ WARNING: Failed to fetch source for luyoga 1.3-3: failed to clone rock source: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
⚠️ Falling back to .src.rock archive
Error: syncing dependencies with the project lockfile failed.

Caused by:
    failed to build luyoga: failed to compile intermediates from C files: ToolExecError: command did not execute successfully (status code exit status: 1): env -u IPHONEOS_DEPLOYMENT_TARGET LC_ALL="C" "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-macosx" "-mmacosx-version-min=11.3" "-I" "/nix/store/lxli6sbwhkvsr81mwvwy0lpvmm3w4d6w-lua-5.1.5/include" "-w" "-o" "/var/folders/6d/fdn4gm611wv1z32z_qt6nghw0000gn/T/nix-shell.Lxuj1y/Yoga.qvCxtZRmENdl/62b861da44fe2efa-Yoga.o" "-c" "/var/folders/6d/fdn4gm611wv1z32z_qt6nghw0000gn/T/nix-shell.Lxuj1y/luyoga.lFJDcCBIhoz3/luyoga/dist/Yoga.h"

Location:
    /Users/sky/Projects/lux/lux-cli/src/utils/project.rs:58:10
```

If the team agrees that this behavior is incorrect, I can go ahead and implement a fix in a PR. Just let me know :)

### PR DESCRIPTION
**Pull request by SkyLeite**
Closes #957

### CODE REVIEW

**Comment by SkyLeite** [comment]
The use-case I outlined in the original issue is fixed, but unfortunately it broke the following test:

```
lux-tests-nextest>     thread 'lua_rockspec::tests::regression_off_spec_install_binaries' panicked at lux-lib/src/lua_rockspec/mod.rs:1655:9:
lux-tests-nextest>     assertion `left == right` failed
lux-tests-nextest>       left: {"wsapi.cgi": "src/launcher/wsapi.cgi"}
lux-tests-nextest>      right: {"wsapi": "src/launcher/wsapi.cgi"}
```

Is it intended that we're removing the file extension from binaries as well? It doesn't sound right, but I'm not too familiar with the spec

**Comment by mrcjkb** [comment]
> The use-case I outlined in the original issue is fixed, but unfortunately it broke the following test:
> 
> ```
> lux-tests-nextest>     thread 'lua_rockspec::tests::regression_off_spec_install_binaries' panicked at lux-lib/src/lua_rockspec/mod.rs:1655:9:
> lux-tests-nextest>     assertion `left == right` failed
> lux-tests-nextest>       left: {"wsapi.cgi": "src/launcher/wsapi.cgi"}
> lux-tests-nextest>      right: {"wsapi": "src/launcher/wsapi.cgi"}
> ```
> 
> Is it intended that we're removing the file extension from binaries as well? It doesn't sound right, but I'm not too familiar with the spec

That's okay, you can update the expected value in the test case.
I just ran a test and luarocks keeps the file extension.

File: lux-lib/src/lua_rockspec/mod.rs [hunk 1]
```diff
@@ -1086,7 +1086,7 @@ mod tests {
             .default
             .install
             .lib
-            .get(&LuaModule::from_str("foo.bar").unwrap())
+            .get("foo.bar")
```
Comment (mrcjkb) [inline lux-lib/src/lua_rockspec/mod.rs]: issue: This might be confusing, as it looks like a Lua module. Let's change the field in the rockspec from `["foo.bar"]` to `["foo.so"]`.

**Comment by mrcjkb** [comment]
todo: Please use conventional commits (see `CONTRIBUTING.md`).

**Review by mrcjkb — CHANGES_REQUESTED** [review]
Clippy lints are failing

File: lux-lib/tests/build.rs [hunk 2]
```diff
@@ -418,3 +419,58 @@ async fn test_multiline_command_build() {
...
+        .progress(&bar)
+        .behaviour(Force)
+        .build()
+        .await
+        .unwrap();
+
+    let mut install_path = tokio::fs::read_dir(dir.path().join("5.1")).await.unwrap();
+    let mut luyoga_path = None;
+    while let Some(entry) = install_path.next_entry().await.unwrap() {
+        dbg!(&entry);
```
Comment (mrcjkb) [inline lux-lib/tests/build.rs]: todo: delete debug print

**Comment by mrcjkb** [comment]
note: Windows build failure is unrelated (#960).

File: lux-lib/tests/build.rs (hunk 2 above)
Comment (SkyLeite) [reply lux-lib/tests/build.rs]: Weird, I thought this would get caught by clippy

File: lux-lib/tests/build.rs [hunk 3]
```diff
@@ -418,3 +419,57 @@ async fn test_multiline_command_build() {
...
+        .tree(&tree)
+        .entry_type(tree::EntryType::Entrypoint)
+        .config(&config)
+        .progress(&bar)
+        .behaviour(Force)
+        .build()
+        .await
+        .unwrap();
+
+    let mut install_path = tokio::fs::read_dir(dir.path().join("5.1")).await.unwrap();
```
Comment (mrcjkb) [inline lux-lib/tests/build.rs]: issue: test is failing here

```
thread 'builtin_build_install_include' panicked at lux-lib/tests/build.rs:460:78:
    called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Comment (mrcjkb) [reply lux-lib/tests/build.rs]: I'd suggest using `assert_fs` assertions instead.

Comment (SkyLeite) [reply lux-lib/tests/build.rs]: Oh right, this is assuming the test is run with Lua 5.1. Is it possible to run these integration tests locally, by any chance?

Comment (mrcjkb) [reply lux-lib/tests/build.rs]: Yes, there's a `cargo tt` alias for it.
