### PR TITLE
fix(build/builtin): properly auto-detect modules

### LINKED ISSUE #236: [Bug] auto detected lua modules are not installed if not specified in the install spec
The `BuiltinBuildSpec` auto-detects Lua modules, but they don't appear to get installed if they are not specified in the `InstallSpec`.
For the `luarocks` package, this results in a bunch of empty directories in the install tree.

### PR DESCRIPTION
**Pull request by mrcjkb**
Fixes #236.

### CODE REVIEW

**Comment by mrcjkb** [comment]
Actually, this was just a bug in `LuaModule::from_pathbuf`. No need to autodetect them in the install step.

I've also moved the `build.utils` module from `rockspec.build.utils` to `build.utils`.

**Comment by mrcjkb** [comment]
We should also add a test case.

**Comment by mrcjkb** [comment]
Turns out we should only auto detect modules if no modules are specified (for example, successfully auto detecting modules breaks `luassert`).

File: rocks-lib/src/build/builtin.rs [hunk 1]
```diff
@@ -30,10 +32,11 @@ impl Build for BuiltinBuildSpec {
         progress: &Progress<ProgressBar>,
     ) -> Result<(), Self::Err> {
         // Detect all Lua modules
-        let modules = autodetect_modules(build_dir)
-            .into_iter()
-            .chain(self.modules)
-            .collect::<HashMap<_, _>>();
+        let modules = if self.modules.is_empty() {
```
Comment (vhyrro) [inline rocks-lib/src/build/builtin.rs:35]: question(non-blocking): is this luarocks's behaviour too? Is there no situation where a few modules are defined by the rockspec author and they "expect" the rest to be autodetected? Given the amount of wacky code we've seen it might be worth checking haha

File: rocks-lib/Cargo.toml [hunk 2]
```diff
@@ -49,6 +49,7 @@ thiserror = "2.0.0"
 gpgme = "0.11.0"
 futures = "0.3.31"
 async-recursion = "1.1.1"
+predicates = "3.1.2"
```
Comment (vhyrro) [inline rocks-lib/Cargo.toml:52]: issue: I only see this used in tests. Should this be part of `dev-dependencies` instead?

File: rocks-lib/src/build/builtin.rs (hunk 1 above)
Comment (mrcjkb) [reply rocks-lib/src/build/builtin.rs:35]: I'm not sure. 
I tried installing `luassert` and it failed if using both the rockspec modules and the auto-detected modules.

Comment (mrcjkb) [reply rocks-lib/src/build/builtin.rs]: Done. Excluding paths from the `ModuleSpec` seems to solve the problem.
